name: tvchart-api
type: laravel
docroot: public
php_version: "8.1"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
  type: postgres
  version: "14"
nfs_mount_enabled: false
mutagen_enabled: false
use_dns_when_possible: true
timezone: Europe/Berlin
composer_version: "2"
web_environment: []
nodejs_version: "16"
